import { existsSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import fg from 'fast-glob';
import { isValidRoutePath } from '@hyperspan/framework/utils';
import type { Adapter } from '@hyperspan/framework';
import { nodeAdapter } from '@hyperspan/adapter-node';

export type RouteModuleSpec = {
  relativeFilePath: string;
  importPath: string;
  importId: string;
};

function toImportId(relativeFilePath: string): string {
  return `__hs_${relativeFilePath.replace(/[^a-zA-Z0-9]+/g, '_')}`;
}

/**
 * Collect app route/action files for static import in the generated server entry.
 */
export async function collectRouteModuleSpecs(
  root: string,
  appDir: string
): Promise<RouteModuleSpec[]> {
  const specs: RouteModuleSpec[] = [];
  const normalizedAppDir = appDir.replace(/^\.\//, '');

  for (const dir of ['routes', 'actions'] as const) {
    const directoryPath = join(root, appDir, dir);
    if (!existsSync(directoryPath)) continue;

    const files = await fg('**/*.{ts,tsx,js,jsx}', {
      cwd: directoryPath,
      onlyFiles: true,
    });

    for (const relativeFilePath of files) {
      if (!isValidRoutePath(relativeFilePath)) continue;
      specs.push({
        relativeFilePath,
        importPath: `../${normalizedAppDir}/${dir}/${relativeFilePath}`.replace(/\\/g, '/'),
        importId: toImportId(`${dir}_${relativeFilePath}`),
      });
    }
  }

  return specs;
}

function generateCreateHyperspanServerBody(routeSpecs: RouteModuleSpec[]): string {
  const importLines = routeSpecs
    .map((spec) => `import ${spec.importId} from '${spec.importPath}';`)
    .join('\n');

  const moduleEntries = routeSpecs
    .map((spec) => `  { file: '${spec.relativeFilePath}', mod: ${spec.importId} },`)
    .join('\n');

  return `${importLines}

const __hs_routeModules = [
${moduleEntries}
];

export async function createHyperspanServer() {
  setAssetManifest(manifest);
  const server = await createServer({
    ...hyperspanConfig,
    publicDir: './dist',
  });

  await initServerRoutes(server, hyperspanConfig, (server) => {
    registerRouteModules(server, __hs_routeModules, manifest);
  });

  return server;
}`;
}

export function resolveDeployAdapter(adapter?: Adapter): Adapter {
  return adapter ?? nodeAdapter();
}

export function generateServerSource(options: {
  routeSpecs: RouteModuleSpec[];
  configImportPath: string;
}): string {
  const { routeSpecs, configImportPath } = options;
  const body = generateCreateHyperspanServerBody(routeSpecs);

  return `// @generated by @hyperspan/vite-plugin — do not edit
import { createServer, setAssetManifest, initServerRoutes } from '@hyperspan/framework';
import { registerRouteModules } from '@hyperspan/framework/routes';
import hyperspanConfig from '${configImportPath}';
import manifest from './manifest.json';
${body}

const __hs_entry = hyperspanConfig.deployAdapter.createEntry({
  createHyperspanServer,
  config: hyperspanConfig,
});

export async function start(options: { port?: number } = {}) {
  return __hs_entry.start?.(options);
}

export default __hs_entry;
`;
}

export async function writeServerEntry(options: {
  root: string;
  outDir: string;
  appDir: string;
  configFile?: string;
}): Promise<void> {
  const { root, outDir, appDir, configFile } = options;

  const routeSpecs = await collectRouteModuleSpecs(root, appDir);
  if (routeSpecs.length === 0) {
    return;
  }

  const configPath = configFile ?? join(root, 'hyperspan.config.ts');
  const configImportPath = relative(outDir, configPath).replace(/\\/g, '/');

  const source = generateServerSource({ routeSpecs, configImportPath });
  writeFileSync(join(outDir, 'server.ts'), source);
}
