import { existsSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import fg from 'fast-glob';
import { isValidRoutePath } from '@hyperspan/framework/utils';
import type { Hyperspan as HS } from '@hyperspan/framework';

export type RouteModuleSpec = {
  relativeFilePath: string;
  importPath: string;
  importId: string;
};

function toImportId(relativeFilePath: string): string {
  return `__hs_${relativeFilePath.replace(/[^a-zA-Z0-9]+/g, '_')}`;
}

/**
 * Collect app route/action files for static import in the generated server entry.
 */
export async function collectRouteModuleSpecs(
  root: string,
  appDir: string
): Promise<RouteModuleSpec[]> {
  const specs: RouteModuleSpec[] = [];
  const normalizedAppDir = appDir.replace(/^\.\//, '');

  for (const dir of ['routes', 'actions'] as const) {
    const directoryPath = join(root, appDir, dir);
    if (!existsSync(directoryPath)) continue;

    const files = await fg('**/*.{ts,tsx,js,jsx}', {
      cwd: directoryPath,
      onlyFiles: true,
    });

    for (const relativeFilePath of files) {
      if (!isValidRoutePath(relativeFilePath)) continue;
      specs.push({
        relativeFilePath,
        importPath: `../${normalizedAppDir}/${dir}/${relativeFilePath}`.replace(/\\/g, '/'),
        importId: toImportId(`${dir}_${relativeFilePath}`),
      });
    }
  }

  return specs;
}

function generateCreateHyperspanServerBody(routeSpecs: RouteModuleSpec[]): string {
  const importLines = routeSpecs
    .map((spec) => `import ${spec.importId} from '${spec.importPath}';`)
    .join('\n');

  const moduleEntries = routeSpecs
    .map((spec) => `  { file: '${spec.relativeFilePath}', mod: ${spec.importId} },`)
    .join('\n');

  return `${importLines}

const __hs_routeModules = [
${moduleEntries}
];

export async function createHyperspanServer() {
  setAssetManifest(manifest);
  const server = await createServer({
    ...hyperspanConfig,
    publicDir: './dist',
  });

  if (hyperspanConfig.beforeRoutesAdded) {
    hyperspanConfig.beforeRoutesAdded(server);
  }

  registerRouteModules(server, __hs_routeModules, manifest);

  if (hyperspanConfig.afterRoutesAdded) {
    hyperspanConfig.afterRoutesAdded(server);
  }

  return server;
}`;
}

function generateNodeStartExport(): string {
  return `
export async function start(options: { port?: number } = {}) {
  if (hyperspanConfig.beforeServerCreate) {
    await hyperspanConfig.beforeServerCreate({ env: process.env });
  }
  const server = await createHyperspanServer();
  return startNodeServer(server, { port: options.port ?? 3000, publicDir: './dist' });
}
`;
}

function generateBunStartExport(): string {
  return `
export async function start(options: { port?: number } = {}) {
  if (hyperspanConfig.beforeServerCreate) {
    await hyperspanConfig.beforeServerCreate({ env: process.env });
  }
  const server = await createHyperspanServer();
  return startBunServer(server, { port: options.port ?? 3000 });
}
`;
}

function generateCloudflareWorkerExport(): string {
  return `
let __hs_appPromise: ReturnType<typeof createCloudflareHandler> | null = null;

export default {
  async fetch(request: Request, env: unknown): Promise<Response> {
    __hs_appPromise ??= (async () => {
      if (hyperspanConfig.beforeServerCreate) {
        await hyperspanConfig.beforeServerCreate({ env });
      }
      const server = await createHyperspanServer();
      const { ASSETS } = env as { ASSETS?: { fetch: (request: Request) => Promise<Response> } };
      return createCloudflareHandler(server, { assets: ASSETS });
    })();
    const app = await __hs_appPromise;
    return app.fetch(request);
  },
} satisfies ExportedHandler;
`;
}

function adapterImports(deployTarget: HS.DeployTarget): string {
  switch (deployTarget) {
    case 'node':
      return "import { startNodeServer } from '@hyperspan/adapter-node';\n";
    case 'bun':
      return "import { startBunServer } from '@hyperspan/adapter-bun';\n";
    case 'cloudflare':
      return "import { createCloudflareHandler } from '@hyperspan/adapter-cloudflare';\n";
  }
}

function targetExport(deployTarget: HS.DeployTarget): string {
  switch (deployTarget) {
    case 'node':
      return generateNodeStartExport();
    case 'bun':
      return generateBunStartExport();
    case 'cloudflare':
      return generateCloudflareWorkerExport();
  }
}

export function generateServerSource(options: {
  routeSpecs: RouteModuleSpec[];
  configImportPath: string;
  deployTarget: HS.DeployTarget;
}): string {
  const { routeSpecs, configImportPath, deployTarget } = options;

  const body = generateCreateHyperspanServerBody(routeSpecs);
  const tailExport = targetExport(deployTarget);

  return `// @generated by @hyperspan/vite-plugin — do not edit
import { createServer, setAssetManifest } from '@hyperspan/framework';
import { registerRouteModules } from '@hyperspan/framework/routes';
import hyperspanConfig from '${configImportPath}';
import manifest from './manifest.json';
${adapterImports(deployTarget)}
${body}
${tailExport}`;
}

export async function writeServerEntry(options: {
  root: string;
  outDir: string;
  appDir: string;
  configFile?: string;
  deployTarget?: HS.DeployTarget;
}): Promise<void> {
  const { root, outDir, appDir, configFile, deployTarget = 'node' } = options;
  const routeSpecs = await collectRouteModuleSpecs(root, appDir);
  if (routeSpecs.length === 0) {
    return;
  }

  const configPath = configFile ?? join(root, 'hyperspan.config.ts');
  const configImportPath = relative(outDir, configPath).replace(/\\/g, '/');

  const source = generateServerSource({ routeSpecs, configImportPath, deployTarget });
  writeFileSync(join(outDir, 'server.ts'), source);
}
