import { existsSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import fg from 'fast-glob';
import { isValidRoutePath } from '@hyperspan/framework/utils';
import type { Adapter, ServerEntrySlots, ServerEntryTemplate } from '@hyperspan/framework';
import { nodeAdapter } from '@hyperspan/adapter-node';

export type RouteModuleSpec = {
  relativeFilePath: string;
  importPath: string;
  importId: string;
};

function toImportId(relativeFilePath: string): string {
  return `__hs_${relativeFilePath.replace(/[^a-zA-Z0-9]+/g, '_')}`;
}

function emitSlot(value: string | null | undefined): string {
  if (value == null || value === '') return '';
  return value.endsWith('\n') ? value : `${value}\n`;
}

/**
 * Collect app route/action files for static import in the generated server entry.
 */
export async function collectRouteModuleSpecs(
  root: string,
  appDir: string
): Promise<RouteModuleSpec[]> {
  const specs: RouteModuleSpec[] = [];
  const normalizedAppDir = appDir.replace(/^\.\//, '');

  for (const dir of ['routes', 'actions'] as const) {
    const directoryPath = join(root, appDir, dir);
    if (!existsSync(directoryPath)) continue;

    const files = await fg('**/*.{ts,tsx,js,jsx}', {
      cwd: directoryPath,
      onlyFiles: true,
    });

    for (const relativeFilePath of files) {
      if (!isValidRoutePath(relativeFilePath)) continue;
      specs.push({
        relativeFilePath,
        importPath: `../${normalizedAppDir}/${dir}/${relativeFilePath}`.replace(/\\/g, '/'),
        importId: toImportId(`${dir}_${relativeFilePath}`),
      });
    }
  }

  return specs;
}

export function resolveDeployAdapter(adapter?: Adapter): Adapter {
  return adapter ?? nodeAdapter();
}

/**
 * Build the shared `dist/server.ts` bootstrap. Adapters call this with slots
 * (especially `afterFileContent`) to produce the platform entry file.
 */
export function createServerEntryTemplate(options: {
  routeSpecs: RouteModuleSpec[];
  configImportPath: string;
}): ServerEntryTemplate {
  const { routeSpecs, configImportPath } = options;
  const importLines = routeSpecs
    .map((spec) => `import ${spec.importId} from '${spec.importPath}';`)
    .join('\n');

  const moduleEntries = routeSpecs
    .map((spec) => `  { file: '${spec.relativeFilePath}', mod: ${spec.importId} },`)
    .join('\n');

  return (
    slots: ServerEntrySlots = {}
  ) => `${emitSlot(slots.beforeFileContent)}// @generated by @hyperspan/vite-plugin — do not edit
import { createServer, setAssetManifest, initServerRoutes, type ServerCreateContext } from '@hyperspan/framework';
import { registerRouteModules } from '@hyperspan/framework/routes';
import hyperspanConfig from '${configImportPath}';
import manifest from './manifest.json';
${importLines}

const __hs_routeModules = [
${moduleEntries}
];

export async function createHyperspanServer({ env }: ServerCreateContext) {
  setAssetManifest(manifest);
  await hyperspanConfig.beforeServerCreate?.({ env });
${emitSlot(slots.beforeCreateServer)}  const server = await createServer({
    ...hyperspanConfig,
    publicDir: './dist',
  });
${emitSlot(slots.afterCreateServer)}
  await initServerRoutes(server, hyperspanConfig, (server) => {
${emitSlot(slots.beforeRoutes)}    registerRouteModules(server, __hs_routeModules, manifest);
${emitSlot(slots.afterRoutes)}  });

  return server;
}
${emitSlot(slots.afterFileContent)}`;
}

export async function writeServerEntry(options: {
  root: string;
  outDir: string;
  appDir: string;
  configFile?: string;
  adapter?: Adapter;
}): Promise<void> {
  const { root, outDir, appDir, configFile, adapter } = options;

  const routeSpecs = await collectRouteModuleSpecs(root, appDir);
  if (routeSpecs.length === 0) {
    return;
  }

  const configPath = configFile ?? join(root, 'hyperspan.config.ts');
  const configImportPath = relative(outDir, configPath).replace(/\\/g, '/');
  const template = createServerEntryTemplate({ routeSpecs, configImportPath });
  const source = await resolveDeployAdapter(adapter).renderServerEntry(template);
  writeFileSync(join(outDir, 'server.ts'), source);
}
